name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: schoulten/r4.4.0:main-a250750768bd1e25f8a46bf08cb27d977b1ffa8e
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      - name: Run ELT code
        run: |
          source("R/extract.R")
          download_ftp(url = "ftp://ftp.mtps.gov.br/pdet/microdados/NOVO%20CAGED/2020/202001/CAGEDMOV202001.7z", dest_dir = "data")
        shell: Rscript {0}
      - name: Commit & Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "ELT workflow run" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

