name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: schoulten/r4.4.0:main-a250750768bd1e25f8a46bf08cb27d977b1ffa8e
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      - name: Run ELT code
        run: |
          source("extract.R")
          download_ftp(
          url = "https://ftp.ibge.gov.br/Precos_Indices_de_Precos_ao_Consumidor/IPCA/Resultados_por_Subitem/2023/ipca_202312Subitem.zip", 
          dest_dir = "data"
          )
        shell: Rscript {0}
      - name: Commit & Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "ELT workflow run" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

