name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: schoulten/r4.4.0:main-a250750768bd1e25f8a46bf08cb27d977b1ffa8e
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      - name: Run ELT code
        run: |
          source("R/extract.R")
          caged_urls <- map_content()
          download_ftp(url = caged_urls[1:2], dest_dir = "data")
        shell: Rscript {0}
